class Agent:
    def __init__(self, agent_id, cash, holdings):
        ...
    
    def decide_order(self, market):
        ...
    
    def apply_trade(self, price, quantity):
        ...
    
    def wealth(self, price):
        ....

class FundamentalTrader():
    ...

class MomentumTrader():
    ...

